#!/usr/bin/env bash

while true; do
    version=$(dwm -v 2>&1)

    if ping -c 1 -W 1 8.8.8.8 > /dev/null 2>&1; then
        net_status="Online"
    else
        net_status="Offline"
    fi

    if nc -z localhost 3000 > /dev/null 2>&1; then
        server_status="Server: UP"
    else
        server_status="Server: DOWN"
    fi

    xsetroot -name "$version | Net: $net_status | $server_status"
    sleep 5
done
