#!/bin/bash

track_changes () 
{ 
    local changed_files=("$@");
    local updated_at=$(date -u +"%Y-%m-%dT%H:%M:%SZ");
    local lock_data=$(jq -n --argjson files "$(printf '%s
' "${changed_files[@]}" | jq -R . | jq -s .)"         --arg updatedAt "$updated_at" '{modifiedFiles: $files, updatedAt: $updatedAt}');
    echo "$lock_data" > "$LOCK_FILE";
    local log_data=$(jq -n --argjson files "$(printf '%s
' "${changed_files[@]}" | jq -R . | jq -s .)"         --arg updatedAt "$updated_at" '{changedFiles: $files, updatedAt: $updatedAt}');
    echo "$log_data" > "$OUTPUT_FILE"
}

track_changes_after_commit() {
    local changed_files=($(git diff --name-only HEAD^ HEAD))
    if [ ${#changed_files[@]} -gt 0 ]; then
        track_changes "${changed_files[@]}"
    fi
}

track_changes_after_commit
